export default  [
    {   
        "id": "1",
        "name":"BMW z4 2003г",
        "engine": "2.5л, АКПП 192л/с",
        "fuel": " Бензин",
        "consumption": "9л/100км",
        "price":"8499р",
        "src": "/img/bmw/bmw.jpg",
        "srcHover": "/img/bmw/bmwHover.jpg",
        "description":"Родстер-Кабриолет",
    },
    {   
        "id": "2",
        "name":"Toyota Corolla verso",
        "engine": "1.8л, АКПП 128л/с",
        "fuel": " Бензин",
        "consumption": "8л/100км",
        "price":"8499р",
        "src": "/img/toyota-corolla/toyota.jpg",
        "srcHover": "/img/toyota-corolla/toyotaHover.jpg",
        "description":"Минивэн",
    },
    {   
        "id": "3",
        "name":"Kia Rio 2017г",
        "engine": "1.6л, АКПП 123л/с",
        "fuel": " Бензин",
        "consumption": "7л/100км",
        "price":"8499р",
        "src": "/img/kia/kia.jpg",
        "srcHover": "/img/kia/kiaHover.jpg",
        "description":"Седан",
    },
    {   
        "id": "4",
        "name":"Nissan micra, 2008г",
        "engine": "1.2л , АКПП 80л/с",
        "fuel": " Бензин",
        "consumption": "5,9л/100км",
        "price":"1499р",
        "src": "/img/nissan/nissan.jpg",
        "srcHover": "/img/nissan/nissanHover.jpg",
        "description":"Хэтчбек",
    },
    {   
        "id": "5",
        "name":"Nissan note, 2012г",
        "engine": "1.6л, АКПП 110л/с",
        "fuel": " Бензин",
        "consumption": "6.5л/100км",
        "price":"2499р",
        "src": "/img/Nissan-Note/note.jpg",
        "srcHover": "/img/Nissan-Note/noteHover.jpg",
        "description":"Хэтчбек",
    },
    {   
        "id": "6",
        "name":"Skoda rapid 2015г",
        "engine": "1.6л, МКПП 110л/с",
        "fuel": " Бензин",
        "consumption": "6л/100км",
        "price":"8499р",
        "src": "/img/shkoda/skoda.jpg",
        "srcHover": "/img/shkoda/skodaHover.jpg",
        "description":"Седан",
    }
]