export default  [
    {   
        "id": "1",
        "name":"BMW z4 2003г",
        "engine": "2.5л, АКПП 192л/с",
        "fuel": " Бензин",
        "consumption": "9л/100км",
        "price1":"1-4 суток 8500р",
        "price2":"5-9 суток 7500р",
        "price3":"10-31 суток 7000р",
        "price4":"от 31 суток - 6500р",
        //Фото на главной странице
        "src": "/img/bmw/bmw.jpg",
        "srcHover": "/img/bmw/bmwHover.jpg",
        /*--------------------------------- */
        "description":"Родстер-Кабриолет",
        //Фото в слайдере в разделе подробнее
        "img1": "/img/bmw/bmw2.jpg",
        "img2": "/img/bmw/bmw3.jpg",
        "img3": "/img/bmw/bmw4.jpg",
        "img4": "",
        "img5": "",
        "img6": "",
        "img7": "",
        "img8": "",
        "img9": "",
        "img10": "",
        /*--------------------------------- */
        "text": "Какое то очень большое большое описание ааааааа ааааааааа ааааааааа аааааа аааааааа",
        //Комплектация
        "comp": "Электрорегулировка зеркал, Электростеклоподъемники",
    },
    {   
        "id": "2",
        "name":"Toyota Corolla verso",
        "engine": "1.8л, АКПП 128л/с",
        "fuel": " Бензин",
        "consumption": "8л/100км",
        "price1":"1-4 суток 3500р",
        "price2":"5-9 суток 3400р",
        "price3":"10-31 суток 3300р",
        "price4":"от 31 суток - 3200р",
        //Фото на главной странице
        "src": "/img/toyota-corolla/toyota.jpg",
        "srcHover": "/img/toyota-corolla/toyotaHover.jpg",
        /*----------------------------------------- */
        "description":"Минивэн",
        //Фото в слайдере в разделе подробнее
        "img1": "/img/toyota-corolla/toyota2.jpg",
        "img2": "/img/toyota-corolla/toyota3.jpg",
        "img3": "/img/toyota-corolla/toyota4.jpg",
        "img4": "/img/toyota-corolla/toyota5.jpg",
        "img5": "/img/toyota-corolla/toyota6.jpg",
        "img6": "/img/toyota-corolla/toyota7.jpg",
        "img7": "",
        "img8": "",
        "img9": "",
        "img10": "",
        /*----------------------------------------- */
        "text": "Какое то очень большое большое описание аааааааа ааааааааааааа аааааааааа аааааааа",
        //Комплектация
        "comp": "Парктроники задние, Электрорегулировка зеркал, Электростеклоподъемники, Бортовой компьютер, Климат-контроль",
    },
    {   
        "id": "3",
        "name":"Kia Rio 2017г",
        "engine": "1.6л, АКПП 123л/с",
        "fuel": " Бензин",
        "consumption": "7л/100км",
        "price1":"1-4 суток 1900р",
        "price2":"5-9 суток 1800р",
        "price3":"10-31 суток 1700р",
        "price4":"от 31 суток - 1600р",
        "src": "/img/kia/kia.jpg",
        "srcHover": "/img/kia/kiaHover.jpg",
        "description":"Седан",
        "img1": "/img/kia/kia2.jpg",
        "img2": "/img/kia/kia3.jpg",
        "img3": "",
        "img4": "",
        "img5": "",
        "img6": "",
        "img7": "",
        "img8": "",
        "img9": "",
        "img10": "",
        "text": "Какое то очень большое большое описание аааааааа ааааааааааааааа аааааааа аааааааа",
        //Комплектация
        "comp": "Подогрев руля, Электрорегулировка зеркал, Электростеклоподъемники, Бортовой компьютер",
    },
    {   
        "id": "4",
        "name":"Nissan micra, 2008г",
        "engine": "1.2л , АКПП 80л/с",
        "fuel": " Бензин",
        "consumption": "5,9л/100км",
        "price1":"1-4 суток 1700р",
        "price2":"5-9 суток 1600р",
        "price3":"10-31 суток 1500р",
        "price4":"от 31 суток - 1400р",
        "src": "/img/nissan/nissan.jpg",
        "srcHover": "/img/nissan/nissanHover.jpg",
        "description":"Хэтчбек",
        "img1": "/img/nissan/nissan2.jpg",
        "img2": "/img/nissan/nissan3.jpg",
        "img3": "",
        "img4": "",
        "img5": "",
        "img6": "",
        "img7": "",
        "img8": "",
        "img9": "",
        "img10": "",
        "text": "Какое то очень большое большое описание аааааааааа аааааааа аааааааааа ааааааааааа",
        //Комплектация
        "comp": "Парктроники задние, Электрорегулировка зеркал, Электростеклоподъемники, Бортовой компьютер",
    },
    {   
        "id": "5",
        "name":"Nissan note, 2012г",
        "engine": "1.6л, АКПП 110л/с",
        "fuel": " Бензин",
        "consumption": "6.5л/100км",
        "price1":"1-4 суток 1900р",
        "price2":"5-9 суток 1800р",
        "price3":"10-31 суток 1700р",
        "price4":"от 31 суток - 1600р",
        "src": "/img/Nissan-Note/note.jpg",
        "srcHover": "/img/Nissan-Note/noteHover.jpg",
        "description":"Хэтчбек",
        "img1": "/img/Nissan-Note/note2.jpg",
        "img2": "/img/Nissan-Note/note3.jpg",
        "img3": "",
        "img4": "",
        "img5": "",
        "img6": "",
        "img7": "",
        "img8": "",
        "img9": "",
        "img10": "",
        "text": "Какое то очень большое большое описание ааааааа аааааааааа аааааааа ааааа ааааааааа",
        //Комплектация
        "comp": "Парктроники задние, Электрорегулировка зеркал, Электростеклоподъемники, Бортовой компьютер",
    },
    {   
        "id": "6",
        "name":"Skoda rapid 2015г",
        "engine": "1.6л, МКПП 110л/с",
        "fuel": " Бензин",
        "consumption": "6л/100км",
        "price1":"1-4 суток 1800р",
        "price2":"5-9 суток 1700р",
        "price3":"10-31 суток 1600р",
        "price4":"от 31 суток - 1500р",
        "src": "/img/shkoda/skoda.jpg",
        "srcHover": "/img/shkoda/skodaHover.jpg",
        "description":"Седан",
        "img1": "/img/shkoda/skoda2.jpg",
        "img2": "/img/shkoda/skoda3.jpg",
        "img3": "/img/shkoda/skoda4.jpg",
        "img4": "",
        "img5": "",
        "img6": "",
        "img7": "",
        "img8": "",
        "img9": "",
        "img10": "",
        "text": "Какое то очень большое большое описание ааааааа ааааааааааа ааааааааааааааа аааааа",
        //Комплектация
        "comp": "Бортовой компьютер, Электрорегулировка зеркал, Электростеклоподъемники",
    }
]